//
//  FiltersInteractor.swift
//  LocatorApp
//
//  Created Ivan Cabezon on 23/8/18.
//  Copyright © 2018 Globile. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

protocol FiltersInteractorProtocol: class {
    var presenter: FiltersPresenterProtocol? { get set }
	var selectedFilters: [Filter] { get }
    func save(with filters: [Filter])
    func deleteAllFilters()
}

class FiltersInteractor: FiltersInteractorProtocol {
    weak var presenter: FiltersPresenterProtocol?
	
    func save(with filters: [Filter]) {
        let filtersString = filters.map { $0.rawValue }
        let userDefault = UserDefaults.standard
        userDefault.set(filtersString, forKey: "currentFilter")
        userDefault.synchronize()
    }
    
	var selectedFilters: [Filter] {
        let userDefault = UserDefaults.standard
        if let setedFilter = userDefault.stringArray(forKey: "currentFilter") {
            let enumArray = setedFilter.map { Filter(rawValue: $0)! }
            return enumArray
        }
        return FilterType.defaultFilters
    }
    
    func deleteAllFilters() {
        let userDefault = UserDefaults.standard
        userDefault.removeObject(forKey: "currentFilter")
    }
    
}

