platform :ios, '11'

use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def legacy_libraries
  pod 'Locker', :path => '../../../../santander-one/Modules/Libraries/Locker'
  pod 'Logger', :path => '../../../../santander-one/Modules/Libraries/Logger'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'SANLibraryV3', :path => '../../../../Modules/Libraries/SANLibraryV3'
  pod 'SANSpainLibrary', :path => '../../../../Modules/Libraries/SANSpainLibrary'
  pod 'SANServicesLibrary', :path => '../../../../santander-one/Modules/Libraries/SANServicesLibrary'
  pod 'CoreTestData', :path => '../../../../santander-one/Modules/Libraries/CoreTestData'
  pod 'Localization', :path => '../../../../santander-one/Localization'
end

def libraries
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'PFM', :path => '../../../../santander-one/Modules/Libraries/PFM'
  pod 'SQLite.swift/SQLCipher', :path => '../../../../santander-one/Modules/Libraries/SQLite.swift'
  pod 'SQLCipher', '4.4.2'
end

def pods
  pod 'ESUI', :path => '../../../Libraries/ESUI'
  pod 'ESCommons', :path => '../../../Libraries/ESCommons'
  pod 'Ecommerce', :path => '../../Ecommerce'
  pod 'QuickSetupES', :path => '../../../../Modules/Libraries/QuickSetupES'
  pod 'QuickSetup', :path => '../../../../santander-one/QuickSetup'
  pod 'UI', :path => '../../../../santander-one/UI'
  pod 'CorePushNotificationsService', :path => '../../../../santander-one/CorePushNotificationsService'
  pod 'Operative', :path => '../../../../santander-one/Operative'
  pod 'BiometryValidator', :path => '../'
  pod 'QuickSetup', :path => '../../../../santander-one/QuickSetup'
  legacy_libraries
  libraries
end

target 'BiometryValidator_Example' do
  pods

  target 'BiometryValidator_Tests' do
    inherit! :search_paths
    pod 'UnitTestCommons', :path => '../../../../santander-one/UnitTestCommons'
  end
end
