use_frameworks!

platform :ios, '10.3'

target 'SanNotificationService_Example' do
  pod 'CoreFoundationLib', :path => '../../../../Modules/Libraries/CoreFoundationLib'
  pod 'CoreDomain', :path => '../../../../Modules/Libraries/CoreDomain'
  pod 'SANLegacyLibrary', :path => '../../../../Modules/Libraries/SANLegacyLibrary'
  pod 'SanNotificationService', :path => '../'
  pod 'Locker', :path => '../../../../Modules/Libraries/Locker'

  target 'SanNotificationService_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
