source 'https://github.com/CocoaPods/Specs.git'



platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!



def shared_pods
  pod 'Fuzi', '3.0.0'
  pod 'Alamofire-Synchronous', '4.0'
  pod 'Alamofire', '4.7.3'
  pod 'SANLegacyLibrary', :path => '../../Libraries/SANLegacyLibrary'
  pod 'SwiftyJSON', '5.0.0'
  pod 'SQLite.swift/SQLCipher', :path => '../SQLite.swift'
  pod 'SQLCipher', '4.4.2'
end



target 'SanLibraryV3' do
    shared_pods
end



target 'SanLibraryV3Tests' do
    shared_pods
end



post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if ["debug"].include? config.name
                config.build_settings['SWIFT_VERSION'] = '5.0'
            end
        end
    end
end
