public enum AccessibilityOnboardingOptions {
    public static let titleCard = "titleCard"
    public static let descriptionCard = "descriptionCard"
    public static let personalAreaBtnLanguage = "personalAreaBtn"
    public static let continueButton = "continueButton"
    public static let finishButton = "onboardingBtnGlobalPosition"
    public static let finishButtonLabel = "generic_button_globalPosition"
    public static let switchButton = "switchButton"
    public static let mapImage = "imgMapOnboarding"
    public static let notificationImage = "imgNotificationsOnboarding"
    public static let faceIdImage = "imgFaceIdOnboarding"
    public static let touchIdImage = "imgTouchIdOnboarding"
    public static let onboardingLabelNotification = "onboarding_label_notifications"
    public static let onboardingTextNotification = "onboarding_text_notifications"
    public static let onboardingSwitchLabelNotification = "onboarding_switchLabel_notifications"
    public static let onBoardingSwitchNotification = "onboarding_switch_notifications"
    public static let onboardingLabelGeolocation = "onboarding_label_geolocation"
    public static let onboardingTextGeolocation = "onboarding_text_geolocation"
    public static let onboardingSwitchLabelGeolocation = "onboarding_switchLabel_geolocation"
    public static let onboardingSwitchGeolocation = "onboarding_switch_geolocation"
    public static let onboardingLabelFaceId = "onboarding_label_faceId"
    public static let onboardingTextFaceId = "onboarding_text_faceId"
    public static let onboardingSwitchLabelFaceId = "onboarding_switchLabel_faceId"
    public static let onboardingSwitchFaceId = "onboarding_switch_faceId"
    public static let onboardingLabelTouchId = "onboarding_label_touchId"
    public static let onboardingTextTouchId = "onboarding_text_touchId"
    public static let onboardingSwitchLabelTouchId = "onboarding_switchLabel_touchId"
    public static let onboardingSwitchTouchId = "onboarding_switch_touchId"
    
}
