public struct AccessibilitySecurityAreaButtons {
    public static let onlineProtectionContainer = "securityAreaViewOnlineProtectionContainer"
    public static let onlineProtectionButton = "securityAreaBtnOnlineProtection"
    public static let fraudViewContainer = "securityAreaViewFraudContainer"
    public static let fraudFrontContainer = "securityAreaViewFraudFrontContainer"
    public static let fraudFrontButton = "securityAreaBtnFraudFrontButton"
    public static let fraudBackButton = "securityAreaBtnFraudBack"
    public static let stolenCardContainer = "securityAreaViewStolenCardContainer"
    public static let stolenCardFrontContainer = "securityAreaViewStolenCardFrontContainer"
    public static let stolenCardFrontButton = "securityAreaBtnStolenCardFrontButton"
    public static let stolenCardSinglePhoneBackContainer = "securityAreaViewStolenCardBackViewSinglePhoneBackContainer"
    public static let stolenCardSinglePhoneBackButton = "securityAreaBtnStolenCardBackViewSinglePhoneButton"
    public static let stolenCardDoublePhoneBackContainer = "securityAreaViewStolenCardDoublePhoneBackContainer"
    public static let stolenCardDoubleFirstPhoneBackButton = "securityAreaBtnStolenCardBackViewDoubleFirstPhoneButton"
    public static let stolenCardDoubleSecondPhoneBackButton = "securityAreaBtnStolenCardBackViewDoubleSecondPhoneButton"
    public static let permissionsContainer = "securityAreaViewPermissionsContainer"
    public static let permissionsButton = "securityAreaBtnPermissions"
    public static let passwordContainer = "securityAreaViewSafeBoxContainer"
    public static let passwordButton = "securityAreaBtnSafeBox"
    public static let travelContainer = "securityAreaViewTravelContainer"
    public static let travelButton = "securityAreaBtnTravel"
    public static let secureDeviceContainer = "securityAreaViewSecureDeviceContainer"
    public static let secureDeviceButton = "securityAreaBtnSecureDevice"
    public static let alertContainer = "securityAreaViewAlertContainer"
    public static let alertButton = "securityAreaBtnAlert"
    private init() {}
}

public enum AccessibilitySecurityAreaAction {
    public static let phoneContainer = "securityAreaViewPhoneActionContainer"
    public static let phoneAction = "securityAreaBtnPhoneAction"
    public static let phoneFilledValue = "securityAreaLabelPhoneFilled"
    public static let mailContainer = "securityAreaViewMailActionContainer"
    public static let mailAction = "securityAreaBtnMailAction"
    public static let mailFilledValue = "securityAreaLabelMailFilled"
    public static let biometryContainer = "securityAreaViewBiometryActionContainer"
    public static let biometryAction = "securityAreaBtnBiometryAction"
    public static let locationContainer = "securityAreaViewLocationActionContainer"
    public static let locationAction = "securityAreaBtnLocationAction"
    public static let secureDeviceContainer = "securityAreaViewSecureDeviceActionContainer"
    public static let secureDeviceAction = "securityAreaBtnSecureDeviceAction"
    public static let secureDeviceFilledValue = "securityAreaLabelSecureDeviceFilled"
    public static let operativityContainer = "securityAreaViewOperativityActionContainer"
    public static let operativityAction = "securityAreaBtnOperativityAction"
    public static let operativityTooltipAction = "securityAreaBtnOperativityTooltipAction"
    public static let operativityFilledValue = "securityAreaLabelOperativityFilled"
    public static let quickBalanceContainer = "securityAreaViewQuickBalanceActionContainer"
    public static let quickBalanceAction = "securityAreaBtnQuickBalanceAction"
    public static let quickBalanceTooltipAction = "securityAreaBtnQuickBalanceTooltipAction"
    public static let quickBalanceChevron = "securityAreaImageQuickBalanceChevron"
    public static let passwordContainer = "securityAreaViewPasswordActionContainer"
    public static let passwordAction = "securityAreaBtnPasswordAction"
    public static let passwordChevron = "securityAreaImagePasswordChevron"
    public static let signatureContainer = "securityAreaViewSignatureActionContainer"
    public static let signatureAction = "securityAreaBtnSignatureAction"
    public static let videoContainer = "securityAreaViewVideoActionContainer"
    public static let videoAction = "securityAreaBtnVideoAction"
    public static let changePinContainer = "securityZoneChangePin"
    public static let changePinTooltip = "securityZoneChangePinTooltip"
    public static let changePinChevron = "securityAreaImageChangePinChevron"
}
