platform :ios, '10.3'
use_frameworks!
target 'UnitTestCommons_Tests' do
  pod 'SANLegacyLibrary', :path => '../../Modules/Libraries/SANLegacyLibrary'
  pod 'CoreDomain', :path => '../../Modules/Libraries/CoreDomain'
  pod 'SANServicesLibrary', :path => '../../Modules/Libraries/SANServicesLibrary'
  pod 'CoreFoundationLib', :path => '../../Modules/Libraries/CoreFoundationLib'
  pod 'RxCombine', :path => '../../Modules/Libraries/RxCombine'
  pod 'UnitTestCommons', :path => '../'
end
