//
//  AnalysisAreaAccessibility.swift
//  Account
//
//  Created by Miguel Ferrer Fornali on 20/1/22.
//

enum AnalysisAreaAccessibility {
    static let analysisLabelMensualFilter = "analysis_label_mensualFilter"
    static let btnGenericChange = "generic_button_change"
    static let genericChangeLabel = "generic_button_change_label"
    static let analysisLabelCards = "analysis_label_cards"
    static let imgFirstBank = "img_firstBank"
    static let oneIcnOthers = "oneIcnOthers"
    static let oneIcnArrowRoundedRight = "oneIcnArrowRoundedRight"
    static let analysisLabelCategoriesTitle = "analysis_label_categoriesTitle"
    static let analysisLabelLastUpdate = "analysis_label_lastUpdate"
    static let analysisAlert = "analysisAlert"
    static let analysisLabelAlert = "analysis_label_alert"
    static let btnGenericUpdate = "generic_button_update"
    static let analysisLabelCategoriesExpenses = "analysis_label_categoriesExpenses"
    static let analysisCardCategoriesList = "analysisCardCategoriesList"
    static let categorizationLabel = "categorization_label"
    static let analysisLabelMovement = "analysis_label_movement"
    static let analysisCardCategoriesListAmount = "analysisCardCategoriesList_Amount"
    static let icnCategoryCat = "icnCategoryCat"
    static let otherSpendsKey = "other_Spends_Label"
    static let analysisFooter = "analysisFooter"
    static let btnAnalysisSettings = "analysis_button_settings"
    static let oneIcnSettings = "oneIcnSettings"
    static let btnAnalysisAddOtherBanks = "analysis_button_addOtherBanks"
    static let oneIcnAddCurrency = "oneIcnAddCurrency"
    static let oneIcnArrowRoundedDown = "oneIcnArrowRoundedDown"
    static let oneIcnArrowRoundedUp = "oneIcnArrowRoundedUp"
    static let analysisViewLoader = "AnalysisViewLoader"
    static let analysisViewSmallLoader = "AnalysisViewSmallLoader"
    static let analysisLoadingCollectingInfo = "analysis_loading_collectingInfo"
    static let analysisLoadingSoon = "analisys_loading_soon"
    static let analysisTitleTooltipExpenses = "analysis_title_tooltipExpenses"
    static let analysisTextTooltipExpenses = "analysis_text_tooltipExpenses"
    static let leftArrowButton = "analysis_button_leftArrow"
    static let rightArrowButton = "analysis_button_rightArrow"
    static let labelPeriod = "analysis_label_period"
    static let chartCollectionCell = "chart_collectionCell"
    static let chartSectorLabel = "chart_sectorLabel"
    static let chartSectorImage = "chart_sectorImage"
    static let chartCenterLabel = "chart_centerLabel"
    static let chartCenterImage = "chart_centerImage"
    static let chartCenterLabelAmount = "chart_centerLabelAmount"
    static let chartCenterLabelCategorySelected = "chart_centerLabel_categorySelected"
    static let chartCenterLabelAmountCategorySelected = "chart_centerLabelAmount_categorySelected"
    static let chartTooltipImage = "chart_tootltipImage"
    static let chartTooltipLabel = "chart_tootltipLabel"
    static let productsConfigurationHeaderTitleLabel = "analysis_label_chooseProducts"
    static let productsConfigurationHeaderSubtitleLabel = "analysis_label_accountsAndCardsConfiguration"
    static let genericLabelAccounts = "generic_label_accounts"
    static let analysisLabelCreditCards = "analysis_label_creditCards"
    static let genericLabelOtherAccounts = "generic_label_otherAccounts"
    static let analysisLabelOtherCreditCards = "analysis_label_otherCreditCards"
    static let genericLabelOtherBanks = "generic_label_otherBanks"
    static let btnAnalysisActivateAll = "analysis_button_activateAll"
    static let labelAnalysisActivateAll = "label_analysis_button_activateAll"
    static let updatePermissionsButton = "analysis_button_updatePermissions"
    static let removeConnectionButton = "analysis_button_removeConnection"
    static let analysisTitleActivatedProduct = "analysis_title_activatedProduct"
    static let analysisTextActivatedProduct = "analysis_text_activatedProduct"
    static let btnAnalysisDeleteConnection = "analysis_button_deleteConnection"
    static let btnGenericCancel = "generic_button_cancel"
    static let btnGenericAccept = "generic_button_accept"
    static let btnAnalysisTryAgain = "analysis_button_tryAgain"
    static let btnAnalysisGoSettings = "analysis_button_goSettings"
    static let oneIcnDeleteBank = "oneIcnDeleteBank"
    static let labelDeleteConnection = "analysis_label_deleteConnection"
    static let labelNotProductBankApp = "analysis_label_notProductBankApp"
    static let oneIcnWarning = "oneIcnWarning"
    static let labelNotDeleteConnection = "analysis_label_notDeleteConnection"
    static let labelTryAgain = "analysis_label_tryAgain"
    static let analysisLogoBank = "analysisLogoBank"
    static let labelRemoveConnectionBank = "analysis_label_removeConnectionBank"
    static let labelRemoveBankProducts = "analysis_label_removeBankProducts"
    static let categoryDetailEmptyView = "analysis_label_categoryDetailEmptyView"
    static let analysisTransactionLabelConcept = "analysisTransactionLabelConcept"
    static let analysisTransactionLabelAmount = "analysisTransactionLabelAmount"
    static let analysisTransactionLabelSubcategory = "analysisTransactionLabelSubcategory"
    static let analysisTransactionLabelImg = "analysisTransactionLabelImg"
    static let analysisTransactionLabelNumber = "analysisTransactionLabelNumber"
    static let analysisTransactionMovementsLabel = "analysisTransactionMovementsLabel"
    static let analysisTransactionpdfButton = "analysisTransactionpdfButton"
    static let analysisTransactionFilterButton = "analysisTransactionFilterButton"
    static let analysisFiltersFloatingButton = "_financialHealth_categoryDetail_filter_applyButton"
    static let analysisFiltersNameFilter = "name_filter_textField"
    static let analysisFiltersStartDate = "startDate_filter_textField"
    static let analysisFiltersEndDate = "endDate_filter_textField"
    static let analysisFiltersStartAmount = "startAmount_filter_textField"
    static let analysisFiltersEndAmount = "endAmount_filter_textField"
}

enum AnalysisAreaOtherBanksBottomSheetAccessibility {
    static let updatePermissionsButton = "analysis_button_updatePermissions"
    static let removeConnectionButton = "analysis_button_removeConnection"
}

enum AnalysisAreaMinimumProductsBottomSheetAccessibility {
    static let analysisTitleActivatedProduct = "analysis_title_activatedProduct"
    static let analysisTextActivatedProduct = "analysis_text_activatedProduct"
}
