platform :ios, '10.3'

use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def legacy_libraries
  pod 'Locker', :path => '../../../../Modules/Libraries/Locker'
  pod 'Logger', :path => '../../../../Modules/Libraries/Logger'
end

def libraries
  pod 'CoreFoundationLib', :path => '../../../../Modules/Libraries/CoreFoundationLib'
  pod 'RxCombine', :path => '../../../../Modules/Libraries/RxCombine'
  pod 'CoreDomain', :path => '../../../../Modules/Libraries/CoreDomain'
  pod 'SQLite.swift/SQLCipher', :path => '../../../../Modules/Libraries/SQLite.swift'
  pod 'SQLCipher', '4.4.2'
  pod 'Kingfisher', '5.15.8'
  pod 'CoreTestData', :path => '../../../../Modules/Libraries/CoreTestData'
  pod 'SANServicesLibrary', :path => '../../../../Modules/Libraries/SANServicesLibrary'
  pod 'OneAuthorizationProcessor', :path => '../../../../Modules/Features/OneAuthorizationProcessor'
end

def pods
  pod 'TransferOperatives/ExampleApp', :path => '../'
  pod 'SANLegacyLibrary', :path => '../../../../Modules/Libraries/SANLegacyLibrary'
  pod 'QuickSetup', :path => '../../../../QuickSetup'
  pod 'UnitTestCommons', :path => '../../../../UnitTestCommons'
  pod 'UI', :path => '../../../../UI'
  pod 'UIOneComponents', :path => '../../../../UIOneComponents'
  pod 'Operative', :path => '../../../../Operative'
  pod 'Localization', :path => '../../../../Localization'
  pod 'CorePushNotificationsService', :path => '../../../../CorePushNotificationsService'
  pod 'PdfCommons', :path => '../../../../PdfCommons'
  pod 'Transfer/ExampleApp', :path => '../../../../Transfer'
  legacy_libraries
  libraries
end


target 'TransferOperatives_Example' do
  pods
end
