source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.3'
use_frameworks!
inhibit_all_warnings!

target 'SANLegacyLibrary' do
  pod 'SANLegacyLibrary', :path => './'

  target 'SANLegacyLibraryTests' do
    inherit! :search_paths

    
  end
end
