-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8q9/KcdoaSLHbxTx
KUv1HzBTaKpuOmOuMjE4CxM5Q9ugCgYIKoZIzj0DAQehRANCAAQbRqJUgW+y5T6C
QMc7uaj9B2M041rqs8BpRZv+3bCjdXEfzaCIkOw/bm+BZAxFdJ45AdSNwJh3/NAu
eQrpmtO9
-----END PRIVATE KEY-----