use_frameworks!

platform :ios, '9.0'

target 'CommonAppExtensions_Example' do
  pod 'CommonAppExtensions', :path => '../'

  target 'CommonAppExtensions_Tests' do
    inherit! :search_paths

    
  end
end
