public class ConfirmationBillTaxesRequest: BSANSoapRequest<ConfirmationBillTaxesRequestParams, ConfirmationBillTaxesHandler, ConfirmationBillTaxesResponse, ConfirmationBillTaxesParser> {
    public static let serviceName = "confirmarPagoRecibo_LA"
    
    public override var serviceName: String {
        return ConfirmationBillTaxesRequest.serviceName
    }
    
    override var nameSpace: String {
        return "http://www.isban.es/webservices/PARETR/Pagorecibos_la/F_paretr_pagorecibos_la/"
    }
    
    override var message: String {
        return "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" "
            + "  xmlns:v1=\"\(nameSpace)\(facade)/v1\">"
            + "  <soapenv:Header>"
            + "    \(getSecurityHeader(params.token))"
            + "  </soapenv:Header>"
            + "  <soapenv:Body>"
            + "  <v1:\(serviceName) facade=\"\(facade)\">"
            + "  <entrada>"
            + "    <tokenPasos>\(params.signatureToken)</tokenPasos>"
            + "    <cuentaCargo>"
            + "      <CENTRO>"
            + "        <EMPRESA>\(params.chargeAccountBankCode)</EMPRESA>"
            + "        <CENTRO>\(params.chargeAccountBranchCode)</CENTRO>"
            + "      </CENTRO>"
            + "      <PRODUCTO>\(params.chargeAccountProduct)</PRODUCTO>"
            + "      <NUMERO_DE_CONTRATO>\(params.chargeAccountContractNumber)</NUMERO_DE_CONTRATO>"
            + "    </cuentaCargo>"
            + "    <centroPago>"
            + "      <EMPRESA>\(BSANHeaderData.DEFAULT_LINKED_COMPANY_SAN_ES_0049)</EMPRESA>"
            + "      <CENTRO/>"
            + "    </centroPago>"
            + "    <impRecibo>"
            + "      <IMPORTE>\(params.billAmountValueForWS)</IMPORTE>"
            + "      <DIVISA>\(params.billAmountCurrency)</DIVISA>"
            + "    </impRecibo>"
            + "    <cuentaDomiciliacion>"
            + "      <CENTRO>"
            + "        <EMPRESA>\(params.directDebitAccountBankCode)</EMPRESA>"
            + "        <CENTRO>\(params.directDebitAccountBranchCode)</CENTRO>"
            + "      </CENTRO>"
            + "      <PRODUCTO>\(params.directDebitAccountProduct)</PRODUCTO>"
            + "      <NUMERO_DE_CONTRATO>\(params.directDebitAccountContractNumber)</NUMERO_DE_CONTRATO>"
            + "    </cuentaDomiciliacion>"
            + "    <recaEmisora>"
            + "      <EMISORA>\(params.issuing)</EMISORA>"
            + "      <PRODUCTO>\(params.product)</PRODUCTO>"
            + "      <SUBTIPO_DE_RECAUDACION>"
            + "        <TIPO_DE_RECAUDACION>\(params.takingsType)</TIPO_DE_RECAUDACION>"
            + "        <CODIGO_DE_SUBTIPO>\(params.takingsSubtype)</CODIGO_DE_SUBTIPO>"
            + "      </SUBTIPO_DE_RECAUDACION>"
            + "    </recaEmisora>"
            + "    <listaFormato>"
            + "    \(formatXMLDesc(list: params.formatDescriptionList))"
            + "    </listaFormato>"
            + "  </entrada>"
            + "  <datosCabecera>"
            + "    <idioma>"
            + "      <IDIOMA_ISO>\(serviceLanguage(BSANHeaderData.DEFAULT_LANGUAGE_ISO_SAN_ES))</IDIOMA_ISO>"
            + "      <DIALECTO_ISO>\(BSANHeaderData.DEFAULT_DIALECT_ISO_SAN_ES)</DIALECTO_ISO>"
            + "    </idioma>"
            + "    <empresaAsociada>\(params.userDataDTO.company ?? "")</empresaAsociada>"
            + "  </datosCabecera>"
            + "  <datosConexion>"
            + "    <canalMarco>\(params.userDataDTO.channelFrame ?? "")</canalMarco>"
            + "    <cliente>"
            + "      <TIPO_DE_PERSONA>\(params.userDataDTO.clientPersonType ?? "")</TIPO_DE_PERSONA>"
            + "      <CODIGO_DE_PERSONA>\(params.userDataDTO.clientPersonCode ?? "")</CODIGO_DE_PERSONA>"
            + "    </cliente>"
            + "  </datosConexion>"
            + " </v1:\(serviceName)>"
            + " </soapenv:Body>"
            + " </soapenv:Envelope>"
    }
}
