use_frameworks!

platform :ios, '11.0'

target 'SelfSignedCertificate_Example' do
  pod 'SelfSignedCertificate', :path => '../'

  target 'SelfSignedCertificate_Tests' do
    inherit! :search_paths

    
  end
end
