platform :ios, '10.3'

use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def legacy_libraries
  pod 'Locker', :path => '../../Modules/Libraries/Locker'
  pod 'Logger', :path => '../../Modules/Libraries/Logger'
end

def libraries
  pod 'CoreTestData', :path => '../../Modules/Libraries/CoreTestData'
  pod 'CoreDomain', :path => '../../Modules/Libraries/CoreDomain'
  pod 'CorePushNotificationsService', :path => '../../CorePushNotificationsService'
  pod 'SQLite.swift/SQLCipher', :path => '../../Modules/Libraries/SQLite.swift'
  pod 'SANLegacyLibrary', :path => '../../Modules/Libraries/SANLegacyLibrary'
  pod 'RxCombine', :path => '../../Modules/Libraries/RxCombine'
  pod 'CoreFoundationLib', :path => '../../Modules/Libraries/CoreFoundationLib'
  pod 'SANServicesLibrary', :path => '../../Modules/Libraries/SANServicesLibrary'
  pod 'SQLCipher', '4.4.3'
  pod 'RxCombine', :path => '../../Modules/Libraries/RxCombine'
end

def pods
  pod 'QuickSetup', :path => '../../QuickSetup'
  pod 'Localization', :path => '../../Localization'
  pod 'UI', :path => '../../UI'
  pod 'Loans/ExampleApp', :path => '../'
  pod 'Loans', :path => '../', :testspecs => ['Tests']
  pod 'Loans/ExampleApp', :path => '../'
  pod 'UIOneComponents', :path => '../../UIOneComponents'
  pod 'Operative', :path => '../../Operative'
  legacy_libraries
  libraries
end

target 'ExampleApp' do
  pods
  target 'ExampleAppTests' do
    inherit! :search_paths
    pod "UnitTestCommons/standard", :path => '../../UnitTestCommons'
  end
end
