enum OpinatorPage: Int {
    case general
    case onOffCard
    case easyPay
    case payLater
    case directMoney
    case payOff
    case ecashGeneric
    case ecashCharge
    case ecashDischarge
    case fundSubscription
    case fundTransfer
    case pensionExtraordinaryContribution
    case pensionPeriodicalContribution
    case tradeStocks
    case buyStocks
    case sellStocks
    case loanChangeAccount
    case loanPartialAmortization
    case mobileRecharge
    case yourManager
    case signCES
    case cashWithdrawal
    case internalTransfer
    case activateCard
    case payBills
    case payTaxes
    case nationalTransfer
    case internationalTransfer
    case nationalPeriodicTransfer
    case nationalDeferredTransfer
    case internationalPeriodicTransfer
    case internationalDeferredTransfer
    case urgentTransfer
    case inmediateTransfer
    case usualTransfer
    case reemittedTransfer
    case internationalReemittedTransfer
    case cancelScheduledTransfer
    case requestPin
    case requestCvv
    case blockCard
    case modifyScheduledTransfer
    case cancelTransfer
    case noSepaSend
    case periodicInternalTransfer
    case deferredInternalTransfer
    case changePaymentMethod
    case limitGestion
    case duplicateBill
    case receiptReturn
    case cancelDirectBilling
    case changeMassiveDirectDebit
    case changeDirectDebit
    case createSepaUsualTransfer
    case createNoSepaUsualTransfer
    case removeSepaUsualTransfer
    case removeNoSepaUsualTransfer
    case updateSepaUsualTransfer
    case updateNoSepaUsualTransfer
    case noSepaReemittedTransfer
    case noSepaUsualTransfer
}
